In [10]:
import pandas as pd
from sklearn.ensemble import ExtraTreesClassifier, RandomForestClassifier, BaggingClassifier, StackingClassifier, VotingClassifier
from sklearn.model_selection import train_test_split
import xgboost as xgb
import tensorflow as tf

# Load dataset

In [11]:
X = pd.read_csv('dataset/train.csv')
y = X.iloc[:,-1]
X = X.iloc[:,:-1]

X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=42, test_size=0.25, stratify=y)
# y_train = tf.one_hot(y_train, depth=5).numpy()
# y_test = tf.one_hot(y_test, depth=5).numpy()

In [12]:
display(X_train.head(), y_train, X.head())

land  logged_in  root_shell  is_host_login  is_guest_login  urgent  \
111037     0          0           0              0               0       0   
93039      0          0           0              0               0       0   
28232      0          0           0              0               0       0   
97494      0          0           0              0               0       0   
76404      0          1           0              0               0       0   

        wrong_fragment  su_attempted  duration  src_bytes  ...  flag_S0  \
111037               0             0       0.0   0.000000  ...      1.0   
93039                0             0       0.0   0.000000  ...      1.0   
28232                0             0       0.0   0.000000  ...      1.0   
97494                0             0       0.0   0.000000  ...      0.0   
76404                0             0       0.0   0.006669  ...      0.0   

        flag_REJ  flag_RSTR  flag_SH  flag_RSTO  flag_S1  flag_RSTOS0  \
111037       0.0        0.0      0.0        0.0      0.0          0.0   
93039        0.0        0.0      0.0        0.0      0.0          0.0   
28232        0.0        0.0      0.0        0.0      0.0          0.0   
97494        1.0        0.0      0.0        0.0      0.0          0.0   
76404        0.0        0.0      0.0        0.0      0.0          0.0   

        flag_S3  flag_S2  flag_OTH  
111037      0.0      0.0       0.0  
93039       0.0      0.0       0.0  
28232       0.0      0.0       0.0  
97494       0.0      0.0       0.0  
76404       0.0      0.0       0.0  

[5 rows x 122 columns]

111037    1
93039     1
28232     1
97494     1
76404     0
         ..
42322     0
57400     1
8618      2
106487    0
35912     1
Name: label, Length: 94479, dtype: int64

land  logged_in  root_shell  is_host_login  is_guest_login  urgent  \
0     0          0           0              0               0       0   
1     0          0           0              0               0       0   
2     0          0           0              0               0       0   
3     0          1           0              0               0       0   
4     0          1           0              0               0       0   

   wrong_fragment  su_attempted  duration  src_bytes  ...  flag_S0  flag_REJ  \
0               0             0       0.0   0.955218  ...      0.0       0.0   
1               0             0       0.0   0.496377  ...      0.0       0.0   
2               0             0       0.0   0.000000  ...      1.0       0.0   
3               0             0       0.0   0.028430  ...      0.0       0.0   
4               0             0       0.0   0.337348  ...      0.0       0.0   

   flag_RSTR  flag_SH  flag_RSTO  flag_S1  flag_RSTOS0  flag_S3  flag_S2  \
0        0.0      0.0        0.0      0.0          0.0      0.0      0.0   
1        0.0      0.0        0.0      0.0          0.0      0.0      0.0   
2        0.0      0.0        0.0      0.0          0.0      0.0      0.0   
3        0.0      0.0        0.0      0.0          0.0      0.0      0.0   
4        0.0      0.0        0.0      0.0          0.0      0.0      0.0   

   flag_OTH  
0       0.0  
1       0.0  
2       0.0  
3       0.0  
4       0.0  

[5 rows x 122 columns]

# Train and test Machine Learning models

In [13]:
clf1 = ExtraTreesClassifier(n_jobs=-1, n_estimators=1000, criterion='entropy')
clf2 = RandomForestClassifier(
    n_jobs=-1, n_estimators=1000, criterion='entropy')

param = {'max_depth':0}
clf3 = xgb.XGBClassifier(param, 1000, objective='multi:softmax')


/home/khoa/khoa/.local/lib/python3.11/site-packages/xgboost/core.py:617: FutureWarning: Pass `objective, use_label_encoder` as keyword args.
  warnings.warn(msg, FutureWarning)
/home/khoa/khoa/.local/lib/python3.11/site-packages/xgboost/sklearn.py:1395: UserWarning: `use_label_encoder` is deprecated in 1.7.0.
  warnings.warn("`use_label_encoder` is deprecated in 1.7.0.")


In [14]:
clf1.fit(X_train, y_train)
clf2.fit(X_train, y_train)
clf3.fit(X_train, y_train)

XGBClassifier(base_score=None, booster=None, callbacks=None,
              colsample_bylevel=None, colsample_bynode=None,
              colsample_bytree=None, early_stopping_rounds=None,
              enable_categorical=False, eval_metric=None, feature_types=None,
              gamma=None, gpu_id=None, grow_policy=None, importance_type=None,
              interaction_constraints=None, learning_rate=None, max_bin=None,
              max_cat_threshold=None, max_cat_to_onehot=None,
              max_delta_step=None, max_depth=None, max_leaves=None,
              min_child_weight=None, missing=nan, monotone_constraints=None,
              n_estimators=100, n_jobs=None, num_parallel_tree=None,
              objective='multi:softprob', predictor=None, ...)

In [15]:
display(clf1.score(X_test, y_test), clf2.score(X_test, y_test), clf3.score(X_test, y_test))

0.9988886772083572

0.9985076522512225

0.9986981647297898

In [16]:
# Save trained model

import pickle

with open('models/ExtraTrees.pickle', 'wb') as handle:
    pickle.dump(clf1, handle)

with open('models/RandomForest.pickle', 'wb') as handle:
    pickle.dump(clf2, handle)

with open('models/XGBoost.pickle', 'wb') as handle:
    pickle.dump(clf3, handle)

In [17]:
# test saved model
import pickle

with open('models/ExtraTrees.pickle', 'rb') as handle:
    clf_et = pickle.load(handle)

with open('models/RandomForest.pickle', 'rb') as handle:
    clf_rf = pickle.load(handle)

with open('models/XGBoost.pickle', 'rb') as handle:
    clf_xgb = pickle.load(handle)

display(clf_et.score(X_test, y_test), clf_rf.score(X_test, y_test), clf_xgb.score(X_test, y_test))

0.9988886772083572

0.9985076522512225

0.9986981647297898

In [18]:
clf_xgb.predict_proba(X_test)

array([[9.99998808e-01, 1.50203562e-07, 1.13712034e-07, 2.41122649e-07,
        6.29499652e-07],
       [9.99625444e-01, 3.61231696e-06, 3.45899258e-04, 8.68929783e-06,
        1.63737750e-05],
       [9.99963522e-01, 1.07838423e-06, 1.71568299e-05, 5.88475541e-06,
        1.23520394e-05],
       ...,
       [1.40518341e-05, 9.99984264e-01, 1.27706232e-06, 9.89577416e-08,
        2.48156084e-07],
       [9.99999046e-01, 2.49153572e-07, 8.07530540e-08, 5.11562064e-07,
        1.40629012e-07],
       [1.21086086e-05, 3.18445444e-07, 9.99986053e-01, 1.83558356e-07,
        1.35495259e-06]], dtype=float32)

In [19]:
tf.cast(clf_rf.predict_proba(X_test), tf.float32)

<tf.Tensor: shape=(31494, 5), dtype=float32, numpy=
array([[1.   , 0.   , 0.   , 0.   , 0.   ],
       [0.996, 0.   , 0.004, 0.   , 0.   ],
       [1.   , 0.   , 0.   , 0.   , 0.   ],
       ...,
       [0.   , 1.   , 0.   , 0.   , 0.   ],
       [1.   , 0.   , 0.   , 0.   , 0.   ],
       [0.   , 0.   , 1.   , 0.   , 0.   ]], dtype=float32)>